import type { ComponentType } from 'react';
import type { IconProps } from '../icons';
import {
  IconTimelineCamera,
  IconTimelineCameraHitchcock,
  IconTimelineCameraPath,
  IconTimelineCameraReset,
  IconTimelineCameraShake,
  IconTimelineCharacterAdd,
  IconTimelineCharacterMove,
  IconTimelineCharacterRemove,
  IconTimelineBlink,
  IconTimelineBgm,
  IconTimelineBlur,
  IconTimelineColorOverlay,
  IconTimelineComposite,
  IconTimelineCompositeModulate,
  IconTimelineCustomAnimation,
  IconTimelineDefault,
  IconTimelineDialogue,
  IconTimelineEnvironment,
  IconTimelineEnvironmentLayer,
  IconTimelineEnvironmentLayerRemove,
  IconTimelineEnvironmentLayerTransform,
  IconTimelineEnvironmentRemove,
  IconTimelineEnvironmentTransform,
  IconTimelineExpression,
  IconTimelineGodrays,
  IconTimelineImageAdd,
  IconTimelineLens,
  IconTimelineLensModulate,
  IconTimelineLighting,
  IconTimelineLook,
  IconTimelineMotion,
  IconTimelineAudioPlay,
  IconTimelineAudioStop,
  IconTimelinePointLight,
  IconTimelinePostProcessing,
  IconTimelineRimLight,
  IconTimelineTextAdd,
  IconTimelineTextRemove,
  IconTimelineTextTransform,
  IconTimelineTransform,
} from '../icons';

type ActionIconComponent = ComponentType<IconProps>;

const withActionIconDefaults = (Icon: ActionIconComponent): ActionIconComponent => {
  const ActionIcon = ({ width = 14, height = 14, ...props }: IconProps) => (
    <Icon width={width} height={height} {...props} />
  );
  return ActionIcon;
};

export const ActionIcons = {
  dialogue: withActionIconDefaults(IconTimelineDialogue),
  playMotion: withActionIconDefaults(IconTimelineMotion),
  setExpression: withActionIconDefaults(IconTimelineExpression),
  moveCharacter: withActionIconDefaults(IconTimelineCharacterMove),
  cameraMotion: withActionIconDefaults(IconTimelineCamera),
  cameraMove: withActionIconDefaults(IconTimelineCamera),
  cameraFollow: withActionIconDefaults(IconTimelineCameraPath),
  cameraPath: withActionIconDefaults(IconTimelineCameraPath),
  cameraShake: withActionIconDefaults(IconTimelineCameraShake),
  cameraHitchcock: withActionIconDefaults(IconTimelineCameraHitchcock),
  cameraReset: withActionIconDefaults(IconTimelineCameraReset),
  setBackground: withActionIconDefaults(IconTimelineEnvironment),
  transformBackground: withActionIconDefaults(IconTimelineEnvironmentTransform),
  removeBackground: withActionIconDefaults(IconTimelineEnvironmentRemove),
  setEnvironmentLayer: withActionIconDefaults(IconTimelineEnvironmentLayer),
  transformEnvironmentLayer: withActionIconDefaults(IconTimelineEnvironmentLayerTransform),
  removeEnvironmentLayer: withActionIconDefaults(IconTimelineEnvironmentLayerRemove),
  addLensFilter: withActionIconDefaults(IconTimelineLens),
  changeLensFilter: withActionIconDefaults(IconTimelineLensModulate),
  resetLensFilters: withActionIconDefaults(IconTimelineLens),
  setCompositeRecipe: withActionIconDefaults(IconTimelineComposite),
  modulateComposite: withActionIconDefaults(IconTimelineCompositeModulate),
  addCharacter: withActionIconDefaults(IconTimelineCharacterAdd),
  removeCharacter: withActionIconDefaults(IconTimelineCharacterRemove),
  transformCharacter: withActionIconDefaults(IconTimelineTransform),
  characterLookAt: withActionIconDefaults(IconTimelineLook),
  characterBlink: withActionIconDefaults(IconTimelineBlink),
  setCharacterRimLight: withActionIconDefaults(IconTimelineRimLight),
  setLighting: withActionIconDefaults(IconTimelineLighting),
  resetLighting: withActionIconDefaults(IconTimelineEnvironmentRemove),
  setBlur: withActionIconDefaults(IconTimelineBlur),
  resetBlur: withActionIconDefaults(IconTimelineEnvironmentLayerRemove),
  setGodrays: withActionIconDefaults(IconTimelineGodrays),
  resetGodrays: withActionIconDefaults(IconTimelineEnvironmentLayerRemove),
  setPostProcessing: withActionIconDefaults(IconTimelinePostProcessing),
  resetPostProcessing: withActionIconDefaults(IconTimelineEnvironmentLayerRemove),
  addColorOverlay: withActionIconDefaults(IconTimelineColorOverlay),
  removeColorOverlay: withActionIconDefaults(IconTimelineEnvironmentRemove),
  clearColorOverlays: withActionIconDefaults(IconTimelineEnvironmentRemove),
  addPointLight: withActionIconDefaults(IconTimelinePointLight),
  removePointLight: withActionIconDefaults(IconTimelineEnvironmentRemove),
  clearPointLights: withActionIconDefaults(IconTimelineEnvironmentLayerRemove),
  playAudio: withActionIconDefaults(IconTimelineAudioPlay),
  stopAudio: withActionIconDefaults(IconTimelineAudioStop),
  setBGM: withActionIconDefaults(IconTimelineBgm),
  addImage: withActionIconDefaults(IconTimelineImageAdd),
  transformImage: withActionIconDefaults(IconTimelineImageAdd),
  removeImage: withActionIconDefaults(IconTimelineImageAdd),
  addTextLayer: withActionIconDefaults(IconTimelineTextAdd),
  transformTextLayer: withActionIconDefaults(IconTimelineTextTransform),
  removeTextLayer: withActionIconDefaults(IconTimelineTextRemove),
  playCustomAnimation: withActionIconDefaults(IconTimelineCustomAnimation),
  default: withActionIconDefaults(IconTimelineDefault),
} as const satisfies Record<string, ActionIconComponent>;

export const PARAM_LABELS: Record<string, string> = {
  speaker: '显示名称',
  speakerId: '绑定角色',
  text: '对话文本',
  voice: '语音文件',
  lipSync: '口型同步',
  duration: '时长',
  durationSeconds: '时长',
  id: '角色 ID',
  motion: '动作名',
  position: '空间坐标',
  scale: '缩放比例',
  rotation: '旋转角度',
  opacity: '不透明度',
  z: '深度 (Z)',
  focusX: '对焦 X',
  focusY: '对焦 Y',
  model: '模型文件',
  enter: '登场动画',
  enterDuration: '登场时长',
  enterEase: '登场缓动',
  exit: '退场动画',
  exitDuration: '退场时长',
  exitEase: '退场缓动',
  image: '背景图片',
  layerId: '环境图层 ID',
  label: '层名',
  layoutMode: '布局模式',
  tileScaleX: '平铺缩放 X',
  tileScaleY: '平铺缩放 Y',
  tileOffsetX: '平铺偏移 X',
  tileOffsetY: '平铺偏移 Y',
  recipeId: '风格配方',
  slot: '作用层',
  targetId: '作用对象',
  semanticOverride: '风格微调',
  advancedOverride: '高级参数',
  zoom: '镜头缩放',
  transition: '切换效果',
  file: '资源路径',
  volume: '音量大小',
  loop: '循环播放',
  expression: '表情名',
  intensity: '强度',
  brightness: '亮度',
  radius: '半径',
  color: '颜色',
  colorStops: '四点颜色',
  colorBlendMode: '混合模式',
  ease: '缓动曲线',
  delay: '延迟',
  smoothing: '平滑度',
  target: '目标坐标',
  keyframes: '关键帧 (JSON)',
  yoyo: '往返播放',
  repeat: '重复次数',
  characterId: '跟随角色',
  offsetX: '偏移 X',
  offsetY: '偏移 Y',
  preset: '光照预设',
  targetCharacter: '对焦角色',
  targetPart: '对焦部位',
  template: '文本框模版',
  screenTarget: '屏幕目标位置',
  zoomStart: '起始变焦',
  zoomEnd: '结束变焦',
  zoomDelta: '变焦增量',
  scaleStart: '起始缩放',
  scaleEnd: '结束缩放',
  angle: '倾斜角度',
  rotations: '旋转圈数',
  direction: '旋转方向',
  to: '目标坐标',
  toY: '目标 Y',
  zoomLevel: '变焦等级',
  fadeIn: '淡入',
  move: '运镜动作',
  easing: '情绪缓动',
  focus: '关注点',
  shakeDirection: '震动方向',
  zIndex: '层级',
  strength: '强度',
  fontFamily: '字体',
  fontSize: '字号',
  stroke: '描边颜色',
  strokeThickness: '描边宽度',
  dropShadow: '开启投影',
  dropShadowColor: '投影颜色',
  dropShadowAlpha: '投影透明度',
  dropShadowBlur: '投影模糊',
  dropShadowDistance: '投影距离',
  style: '动画风格',
  wordWrapWidth: '换行宽度',
  mode: '生效方式',
  warmth: '冷暖',
  bloom: '柔光',
  rgbSplit: '色差',
  blend: '融入度',
  contamination: '环境染色',
  bloomThreshold: '泛光阈值',
  bloomBloomScale: '泛光强度',
  bloomBrightness: '泛光亮度',
  rgbSplitX: '色差 X',
  rgbSplitY: '色差 Y',
  godrayGain: '体积光强度',
  godrayAngle: '体积光角度',
  adjGamma: '伽马',
  adjContrast: '对比度',
  adjSaturation: '饱和度',
  adjBrightness: '亮度',
  adjRed: '红色通道',
  adjGreen: '绿色通道',
  adjBlue: '蓝色通道',
  thickness: '厚度',
  softness: '边缘柔和度',
};
