import type {
  KeyboardShortcutsSettings,
  ShortcutBinding,
  ShortcutCommand,
  ShortcutCommandId,
} from './types';

export const SHORTCUT_COMMANDS: ShortcutCommand[] = [
  {
    id: 'app.playPause',
    label: '播放 / 停止',
    group: '回放',
    description: '切换当前场景播放状态。',
    scope: 'editing',
  },
  {
    id: 'app.frameBackward',
    label: '后退一帧',
    group: '回放',
    description: '按 1/60 秒向前一步。',
    scope: 'editing',
  },
  {
    id: 'app.frameForward',
    label: '前进一帧',
    group: '回放',
    description: '按 1/60 秒向后一步。',
    scope: 'editing',
  },
  {
    id: 'app.save',
    label: '保存场景',
    group: '文件',
    description: '保存当前场景。',
    scope: 'global',
  },
  {
    id: 'app.openProject',
    label: '打开项目',
    group: '文件',
    description: '打开 AeonStagery 项目。',
    scope: 'global',
  },
  {
    id: 'app.export',
    label: '导出',
    group: '文件',
    description: '打开导出面板。',
    scope: 'global',
  },
  {
    id: 'app.undo',
    label: '撤销',
    group: '编辑',
    description: '撤销最近一次语义编辑。',
    scope: 'global',
  },
  {
    id: 'app.redo',
    label: '重做',
    group: '编辑',
    description: '重做最近一次语义编辑。',
    scope: 'global',
  },
  {
    id: 'app.openShortcutSettings',
    label: '打开快捷键设置',
    group: '设置',
    description: '打开设置中的快捷键页。',
    scope: 'global',
  },
  {
    id: 'stage.resetView',
    label: '重置舞台视图',
    group: '舞台',
    description: '将舞台缩放与位置恢复到默认视图。',
    scope: 'editing',
  },
  {
    id: 'timeline.copySelection',
    label: '复制选区',
    group: '时间线',
    description: '复制选中的语义语句块。',
    scope: 'timeline',
  },
  {
    id: 'timeline.pasteAtPlayhead',
    label: '粘贴到播放头',
    group: '时间线',
    description: '将复制的语义片段插入到当前播放头。',
    scope: 'timeline',
  },
  {
    id: 'timeline.duplicateSelection',
    label: '创建副本',
    group: '时间线',
    description: '复制并插入选中语句块的副本。',
    scope: 'timeline',
  },
  {
    id: 'timeline.deleteSelection',
    label: '删除选区',
    group: '时间线',
    description: '删除选中的语义语句块。',
    scope: 'timeline',
  },
  {
    id: 'timeline.splitSelection',
    label: '在播放头处拆分',
    group: '时间线',
    description: '将选中语句块在播放头位置拆分。',
    scope: 'timeline',
  },
  {
    id: 'timeline.alignSelectionToPlayhead',
    label: '对齐到播放头',
    group: '时间线',
    description: '将选区起点移动到当前播放头。',
    scope: 'timeline',
  },
  {
    id: 'timeline.nudgeSelectionLeft',
    label: '选区左移一格',
    group: '时间线',
    description: '将选中语句块向前移动 0.1 秒。',
    scope: 'timeline',
  },
  {
    id: 'timeline.nudgeSelectionRight',
    label: '选区右移一格',
    group: '时间线',
    description: '将选中语句块向后移动 0.1 秒。',
    scope: 'timeline',
  },
  {
    id: 'timeline.selectPrevious',
    label: '选择上一动作',
    group: '时间线',
    description: '选择时间线中的上一个语义动作。',
    scope: 'timeline',
  },
  {
    id: 'timeline.selectNext',
    label: '选择下一动作',
    group: '时间线',
    description: '选择时间线中的下一个语义动作。',
    scope: 'timeline',
  },
  {
    id: 'timeline.zoomIn',
    label: '放大时间线',
    group: '时间线',
    description: '放大当前时间线视图。',
    scope: 'timeline',
  },
  {
    id: 'timeline.zoomOut',
    label: '缩小时间线',
    group: '时间线',
    description: '缩小当前时间线视图。',
    scope: 'timeline',
  },
  {
    id: 'timeline.addMarker',
    label: '添加标记',
    group: '时间线',
    description: '在播放头处添加时间线标记。',
    scope: 'timeline',
  },
];

export const SHORTCUT_COMMAND_BY_ID = new Map(SHORTCUT_COMMANDS.map((command) => [command.id, command]));

export const PREMIERE_SHORTCUT_BINDINGS: Record<ShortcutCommandId, ShortcutBinding[]> = {
  'app.playPause': [{ code: 'Space', key: ' ' }],
  'app.frameBackward': [{ code: 'ArrowLeft', key: 'ArrowLeft' }],
  'app.frameForward': [{ code: 'ArrowRight', key: 'ArrowRight' }],
  'app.save': [{ code: 'KeyS', key: 's', primary: true }],
  'app.openProject': [{ code: 'KeyO', key: 'o', primary: true }],
  'app.export': [{ code: 'KeyM', key: 'm', primary: true }],
  'app.undo': [{ code: 'KeyZ', key: 'z', primary: true }],
  'app.redo': [
    { code: 'KeyZ', key: 'z', primary: true, shift: true },
    { code: 'KeyY', key: 'y', primary: true },
  ],
  'app.openShortcutSettings': [{ code: 'Slash', key: '/', primary: true, shift: true }],
  'stage.resetView': [{ code: 'KeyR', key: 'r' }],
  'timeline.copySelection': [{ code: 'KeyC', key: 'c', primary: true }],
  'timeline.pasteAtPlayhead': [{ code: 'KeyV', key: 'v', primary: true }],
  'timeline.duplicateSelection': [{ code: 'KeyD', key: 'd', primary: true }],
  'timeline.deleteSelection': [
    { code: 'Delete', key: 'Delete' },
    { code: 'Backspace', key: 'Backspace' },
  ],
  'timeline.splitSelection': [{ code: 'KeyK', key: 'k', primary: true }],
  'timeline.alignSelectionToPlayhead': [],
  'timeline.nudgeSelectionLeft': [{ code: 'ArrowLeft', key: 'ArrowLeft', alt: true }],
  'timeline.nudgeSelectionRight': [{ code: 'ArrowRight', key: 'ArrowRight', alt: true }],
  'timeline.selectPrevious': [{ code: 'ArrowUp', key: 'ArrowUp' }],
  'timeline.selectNext': [{ code: 'ArrowDown', key: 'ArrowDown' }],
  'timeline.zoomIn': [
    { code: 'Equal', key: '=' },
    { code: 'NumpadAdd', key: '+' },
  ],
  'timeline.zoomOut': [
    { code: 'Minus', key: '-' },
    { code: 'NumpadSubtract', key: '-' },
  ],
  'timeline.addMarker': [{ code: 'KeyM', key: 'm' }],
};

export const DEFAULT_KEYBOARD_SHORTCUTS_SETTINGS: KeyboardShortcutsSettings = {
  activeProfileId: 'premiere',
  overrides: {},
};
