import { describe, expect, it } from 'vitest';
import {
  SCENE_SCHEMA_VERSION,
  type CompiledAction,
  type CurrentSceneDocument,
} from '../api/types/semantic-scene';
import {
  encodeCompiledActionId,
  sceneDocumentCodec,
  sceneStatementCompiler,
} from '../services/semantic-scene';

function compiledId(statementId: string, outputKey: string): string {
  return encodeCompiledActionId(statementId, undefined, outputKey);
}

function compactAction(action: CompiledAction): Pick<CompiledAction, 'id' | 'time' | 'action' | 'params' | 'source'> {
  return {
    id: action.id,
    time: action.time,
    action: action.action,
    params: action.params,
    source: action.source,
  };
}

const document: CurrentSceneDocument = {
  schemaVersion: SCENE_SCHEMA_VERSION,
  sceneId: 'compiler_golden',
  meta: {
    title: 'Compiler Golden',
    durationSeconds: 40,
    characters: [
      { id: 'tomori', name: 'Tomori', model: 'figure/tomori/model.json' },
    ],
  },
  statements: [
    {
      id: 'dialogue_1',
      time: 0,
      type: 'dialogue',
      params: {
        speakerId: 'tomori',
        text: 'Hello',
        durationSeconds: 1.5,
        voice: 'voice/tomori/hello.ogg',
        style: 'classic',
        lipSync: true,
      },
    },
    {
      id: 'char_enter',
      time: 1,
      type: 'characterPresence',
      params: {
        mode: 'enter',
        id: 'tomori',
        model: 'figure/tomori/model.json',
        position: [0.4, 1],
        transition: 'fade',
        durationSeconds: 0.8,
        ease: 'easeOut',
      },
    },
    {
      id: 'char_transform',
      time: 2,
      type: 'characterTransform',
      params: {
        id: 'tomori',
        position: [0.5, 1],
        scale: 1.1,
        durationSeconds: 0.5,
        ease: 'linear',
      },
    },
    {
      id: 'char_perf',
      time: 3,
      type: 'characterPerformance',
      params: {
        target: 'tomori',
        motion: { kind: 'resource', key: 'nod' },
        expression: 'smile',
        lookAt: {
          target: 'camera',
          point: [0.5, 0.3],
          enabled: true,
          intensity: 0.7,
        },
        blink: {
          enabled: true,
          interval: 2,
        },
      },
    },
    {
      id: 'char_exit',
      time: 4.5,
      type: 'characterPresence',
      params: {
        mode: 'exit',
        id: 'tomori',
        transition: 'fade',
        durationSeconds: 0.6,
        ease: 'easeIn',
      },
    },
    {
      id: 'camera_focus',
      time: 5,
      type: 'camera',
      params: {
        mode: 'focus',
        target: 'tomori',
        targetPart: 'head',
        zoom: { kind: 'delta', value: 0.25 },
        rotation: 3,
        durationSeconds: 0.7,
        ease: 'easeOut',
      },
    },
    {
      id: 'camera_move',
      time: 6,
      type: 'camera',
      params: {
        mode: 'move',
        to: [0.5, 0.6],
        zoom: { kind: 'absolute', value: 1.4 },
        rotation: 1,
        durationSeconds: 0.9,
        ease: 'linear',
      },
    },
    {
      id: 'camera_follow_start',
      time: 7,
      type: 'camera',
      params: {
        mode: 'follow',
        operation: 'start',
        target: 'tomori',
        offset: [0, -0.1],
        smoothing: 0.6,
      },
    },
    {
      id: 'camera_follow_stop',
      time: 8,
      type: 'camera',
      params: {
        mode: 'follow',
        operation: 'stop',
      },
    },
    {
      id: 'camera_path',
      time: 9,
      type: 'camera',
      params: {
        mode: 'path',
        keyframes: [
          { time: 0, position: [0, 0], zoom: 1 },
          { time: 1, position: [0.5, 0.5], zoom: 1.2, label: 'mid' },
        ],
        durationSeconds: 1.5,
        ease: 'smooth',
        loop: true,
        repeat: 2,
        yoyo: true,
      },
    },
    {
      id: 'camera_shake',
      time: 11,
      type: 'camera',
      params: {
        mode: 'shake',
        intensity: 0.4,
        frequency: 8,
        durationSeconds: 0.5,
        decay: true,
        direction: 'horizontal',
      },
    },
    {
      id: 'camera_hitchcock',
      time: 12,
      type: 'camera',
      params: {
        mode: 'hitchcock',
        target: 'tomori',
        targetPart: 'chest',
        screenTarget: [0.45, 0.5],
        zoomStart: 1,
        zoomEnd: 1.3,
        scaleStart: 1,
        scaleEnd: 0.85,
        durationSeconds: 1.1,
        ease: 'easeInOut',
      },
    },
    {
      id: 'camera_reset',
      time: 13.5,
      type: 'camera',
      params: {
        mode: 'reset',
        durationSeconds: 0.4,
        ease: 'smooth',
      },
    },
    {
      id: 'env_set',
      time: 14,
      type: 'environmentLayer',
      params: {
        mode: 'set',
        layerId: 'background',
        image: 'background/classroom.png',
        position: [0.5, 0.5],
        scale: 1,
        durationSeconds: 0.5,
        transition: 'crossFade',
      },
    },
    {
      id: 'env_transform',
      time: 15,
      type: 'environmentLayer',
      params: {
        mode: 'transform',
        layerId: 'background',
        position: [0.55, 0.5],
        scale: 1.05,
        durationSeconds: 0.4,
        ease: 'linear',
      },
    },
    {
      id: 'env_remove',
      time: 16,
      type: 'environmentLayer',
      params: {
        mode: 'remove',
        layerId: 'background',
        durationSeconds: 0.3,
      },
    },
    {
      id: 'visual_filter_add',
      time: 17,
      type: 'filterAdd',
      params: {
        recipeId: 'builtin:cinematic-cold',
        intensity: 0.8,
      },
    },
    {
      id: 'visual_filter_change',
      time: 17.5,
      type: 'filterChange',
      params: {
        fromRecipeId: 'builtin:cinematic-cold',
        recipeId: 'builtin:haze-godray',
        warmth: -0.2,
        durationSeconds: 0.5,
      },
    },
    {
      id: 'visual_filter_reset',
      time: 17.75,
      type: 'filterReset',
      params: { durationSeconds: 0.4 },
    },
    {
      id: 'visual_object_set',
      time: 18,
      type: 'visualStyle',
      params: {
        scope: 'object',
        target: 'tomori',
        slot: 'integration',
        mode: 'set',
        recipeId: 'stage-match',
        blend: 0.7,
      },
    },
    {
      id: 'visual_object_mod',
      time: 18.5,
      type: 'visualStyle',
      params: {
        scope: 'object',
        target: 'tomori',
        slot: 'integration',
        mode: 'modulate',
        contamination: 0.3,
        durationSeconds: 0.4,
      },
    },
    {
      id: 'visual_object_reset',
      time: 19,
      type: 'visualStyle',
      params: {
        scope: 'object',
        target: 'tomori',
        slot: 'integration',
        mode: 'reset',
      },
    },
    {
      id: 'lighting_preset',
      time: 19.5,
      type: 'lighting',
      params: {
        effect: 'preset',
        mode: 'set',
        preset: 'dramatic',
        intensity: 0.9,
      },
    },
    {
      id: 'lighting_preset_reset',
      time: 20,
      type: 'lighting',
      params: {
        effect: 'preset',
        mode: 'reset',
      },
    },
    {
      id: 'lighting_blur',
      time: 20.5,
      type: 'lighting',
      params: {
        effect: 'blur',
        mode: 'set',
        target: 'background',
        intensity: 0.2,
      },
    },
    {
      id: 'lighting_godrays',
      time: 21,
      type: 'lighting',
      params: {
        effect: 'godrays',
        mode: 'set',
        durationSeconds: 0.5,
        angle: 45,
        lacunarity: 2.5,
      },
    },
    {
      id: 'lighting_post_reset',
      time: 22,
      type: 'lighting',
      params: {
        effect: 'post',
        mode: 'reset',
      },
    },
    {
      id: 'lighting_overlay',
      time: 22.5,
      type: 'lighting',
      params: {
        effect: 'overlay',
        mode: 'set',
        id: 'overlay_1',
        color: '#fff',
        intensity: 0.3,
      },
    },
    {
      id: 'lighting_overlay_remove',
      time: 23,
      type: 'lighting',
      params: {
        effect: 'overlay',
        mode: 'remove',
        id: 'overlay_1',
      },
    },
    {
      id: 'lighting_overlay_clear',
      time: 23.5,
      type: 'lighting',
      params: {
        effect: 'overlay',
        mode: 'clear',
      },
    },
    {
      id: 'lighting_point',
      time: 24,
      type: 'lighting',
      params: {
        effect: 'pointLight',
        mode: 'set',
        id: 'point_1',
        color: '#ffe',
        radius: 120,
        x: 0.4,
        y: 0.3,
      },
    },
    {
      id: 'lighting_point_clear',
      time: 24.5,
      type: 'lighting',
      params: {
        effect: 'pointLight',
        mode: 'clear',
      },
    },
    {
      id: 'audio_bgm_play',
      time: 25,
      type: 'audio',
      params: {
        role: 'bgm',
        mode: 'play',
        file: 'bgm/opening.ogg',
        volume: 0.4,
        loop: true,
        fadeIn: 1,
      },
    },
    {
      id: 'audio_bgm_stop',
      time: 26,
      type: 'audio',
      params: {
        role: 'bgm',
        mode: 'stop',
        fadeOut: 0.8,
      },
    },
    {
      id: 'audio_sfx_play',
      time: 27,
      type: 'audio',
      params: {
        role: 'sfx',
        mode: 'play',
        instanceId: 'door',
        file: 'sfx/door.ogg',
        volume: 0.7,
        durationSeconds: 1.2,
      },
    },
    {
      id: 'audio_sfx_stop',
      time: 28,
      type: 'audio',
      params: {
        role: 'sfx',
        mode: 'stop',
        instanceId: 'door',
        fadeOut: 0.2,
      },
    },
    {
      id: 'graphic_image_set',
      time: 29,
      type: 'graphicLayer',
      params: {
        kind: 'image',
        mode: 'set',
        id: 'poster',
        file: 'images/poster.png',
        position: [0.5, 0.5],
      },
    },
    {
      id: 'graphic_image_transform',
      time: 30,
      type: 'graphicLayer',
      params: {
        kind: 'image',
        mode: 'transform',
        id: 'poster',
        scale: 1.2,
        durationSeconds: 0.5,
      },
    },
    {
      id: 'graphic_image_remove',
      time: 31,
      type: 'graphicLayer',
      params: {
        kind: 'image',
        mode: 'remove',
        id: 'poster',
      },
    },
    {
      id: 'graphic_text_set',
      time: 32,
      type: 'graphicLayer',
      params: {
        kind: 'text',
        mode: 'set',
        id: 'caption',
        text: 'Title',
        fontFamily: 'Inter',
        fontSize: 32,
        color: '#fff',
      },
    },
    {
      id: 'graphic_text_transform',
      time: 33,
      type: 'graphicLayer',
      params: {
        kind: 'text',
        mode: 'transform',
        id: 'caption',
        opacity: 0.5,
        durationSeconds: 0.4,
      },
    },
    {
      id: 'graphic_text_remove',
      time: 34,
      type: 'graphicLayer',
      params: {
        kind: 'text',
        mode: 'remove',
        id: 'caption',
      },
    },
    {
      id: 'custom_anim',
      time: 35,
      type: 'customAnimation',
      params: {
        target: 'poster',
        file: 'effects/sparkle.json',
        durationSeconds: 1,
        loop: false,
      },
    },
  ],
};

describe('SceneStatementCompiler golden output', () => {
  it('materializes semantic transition defaults into executable actions', () => {
    const compiled = sceneStatementCompiler.compile(sceneDocumentCodec.parseAndValidate({
      schemaVersion: SCENE_SCHEMA_VERSION,
      sceneId: 'compiler_transition_defaults',
      meta: {
        title: 'Compiler Transition Defaults',
        durationSeconds: 12,
        characters: [{ id: 'tomori', name: 'Tomori', model: 'figure/tomori/model.json' }],
      },
      statements: [
        {
          id: 'enter_default',
          time: 0,
          type: 'characterPresence',
          params: { mode: 'enter', id: 'tomori' },
        },
        {
          id: 'exit_default',
          time: 2,
          type: 'characterPresence',
          params: { mode: 'exit', id: 'tomori' },
        },
        {
          id: 'exit_none',
          time: 3,
          type: 'characterPresence',
          params: { mode: 'exit', id: 'tomori', transition: 'none' },
        },
        {
          id: 'env_set_default',
          time: 4,
          type: 'environmentLayer',
          params: { mode: 'set', layerId: 'background', file: 'background/a.png' },
        },
        {
          id: 'env_remove_default',
          time: 6,
          type: 'environmentLayer',
          params: { mode: 'remove', layerId: 'background' },
        },
        {
          id: 'bgm_play_default',
          time: 7,
          type: 'audio',
          params: { role: 'bgm', mode: 'play', file: 'bgm/theme.ogg' },
        },
        {
          id: 'bgm_stop_default',
          time: 8,
          type: 'audio',
          params: { role: 'bgm', mode: 'stop' },
        },
        {
          id: 'sfx_stop_default',
          time: 9,
          type: 'audio',
          params: { role: 'sfx', mode: 'stop', instanceId: 'door' },
        },
      ],
    }));

    expect(compiled.actions.map(compactAction)).toEqual([
      {
        id: compiledId('enter_default', 'primary'),
        time: 0,
        action: 'addCharacter',
        params: {
          id: 'tomori',
          model: 'figure/tomori/model.json',
          enter: 'fadeIn',
          duration: 0.6,
          enterDuration: 0.6,
        },
        source: { statementId: 'enter_default', outputKey: 'primary' },
      },
      {
        id: compiledId('exit_default', 'primary'),
        time: 2,
        action: 'removeCharacter',
        params: {
          id: 'tomori',
          exit: 'fadeOut',
          duration: 0.6,
          exitDuration: 0.6,
        },
        source: { statementId: 'exit_default', outputKey: 'primary' },
      },
      {
        id: compiledId('exit_none', 'primary'),
        time: 3,
        action: 'removeCharacter',
        params: {
          id: 'tomori',
          exit: 'none',
          duration: 0,
          exitDuration: 0,
        },
        source: { statementId: 'exit_none', outputKey: 'primary' },
      },
      {
        id: compiledId('env_set_default', 'primary'),
        time: 4,
        action: 'setEnvironmentLayer',
        params: {
          layerId: 'background',
          image: 'background/a.png',
          duration: 1,
          transition: 'crossFade',
        },
        source: { statementId: 'env_set_default', outputKey: 'primary' },
      },
      {
        id: compiledId('env_remove_default', 'primary'),
        time: 6,
        action: 'removeEnvironmentLayer',
        params: {
          layerId: 'background',
          duration: 0.6,
          transition: 'fadeOut',
        },
        source: { statementId: 'env_remove_default', outputKey: 'primary' },
      },
      {
        id: compiledId('bgm_play_default', 'primary'),
        time: 7,
        action: 'setBGM',
        params: {
          file: 'bgm/theme.ogg',
          fadeIn: 0.5,
        },
        source: { statementId: 'bgm_play_default', outputKey: 'primary' },
      },
      {
        id: compiledId('bgm_stop_default', 'stop'),
        time: 8,
        action: 'stopAudio',
        params: {
          id: 'bgm',
          fadeOut: 0.5,
        },
        source: { statementId: 'bgm_stop_default', outputKey: 'stop' },
      },
      {
        id: compiledId('sfx_stop_default', 'stop'),
        time: 9,
        action: 'stopAudio',
        params: {
          id: 'door',
          fadeOut: 0.5,
        },
        source: { statementId: 'sfx_stop_default', outputKey: 'stop' },
      },
    ]);
  });

  it('keeps sparse camera companion data valid and resolves its speaker target', () => {
    const compiled = sceneStatementCompiler.compile(sceneDocumentCodec.parseAndValidate({
      schemaVersion: SCENE_SCHEMA_VERSION,
      sceneId: 'compiler_sparse_camera_companion',
      meta: {
        title: 'Sparse Camera Companion',
        characters: [{ id: 'tomori', name: 'Tomori', model: 'figure/tomori/model.json' }],
      },
      statements: [{
        id: 'dialogue_sparse_camera',
        time: 2,
        type: 'dialogue',
        params: { speakerId: 'tomori', text: 'Hello', durationSeconds: 1 },
        companions: [{
          id: 'focus_speaker',
          anchor: 'start',
          offset: 0,
          type: 'camera',
          params: { mode: 'focus', target: '$speaker' },
        }],
      }],
    }));

    expect(compiled.actions.map(compactAction)).toEqual([
      {
        id: compiledId('dialogue_sparse_camera', 'primary'),
        time: 2,
        action: 'dialogue',
        params: {
          speakerId: 'tomori',
          text: 'Hello',
          duration: 1,
        },
        source: { statementId: 'dialogue_sparse_camera', outputKey: 'primary' },
      },
      {
        id: encodeCompiledActionId('dialogue_sparse_camera', 'focus_speaker', 'primary'),
        time: 2,
        action: 'cameraMotion',
        params: {
          move: 'pan',
          easing: 'smooth',
          focus: { character: 'tomori', part: 'head' },
        },
        source: {
          statementId: 'dialogue_sparse_camera',
          companionId: 'focus_speaker',
          outputKey: 'primary',
        },
      },
    ]);
  });

  it('keeps lowerer ids, ordering, and params stable across statement families', () => {
    const compiled = sceneStatementCompiler.compile(sceneDocumentCodec.parseAndValidate(document));

    expect(compiled.actions.map(compactAction)).toEqual([
      {
        id: compiledId('dialogue_1', 'primary'),
        time: 0,
        action: 'dialogue',
        params: {
          speakerId: 'tomori',
          text: 'Hello',
          duration: 1.5,
          voice: 'voice/tomori/hello.ogg',
          style: 'classic',
          lipSync: 'audio',
        },
        source: { statementId: 'dialogue_1', outputKey: 'primary' },
      },
      {
        id: compiledId('char_enter', 'primary'),
        time: 1,
        action: 'addCharacter',
        params: {
          id: 'tomori',
          model: 'figure/tomori/model.json',
          position: [0.4, 1],
          enter: 'fade',
          duration: 0.8,
          enterDuration: 0.8,
          enterEase: 'easeOut',
        },
        source: { statementId: 'char_enter', outputKey: 'primary' },
      },
      {
        id: compiledId('char_transform', 'primary'),
        time: 2,
        action: 'transformCharacter',
        params: {
          id: 'tomori',
          position: [0.5, 1],
          scale: 1.1,
          duration: 0.5,
          ease: 'linear',
        },
        source: { statementId: 'char_transform', outputKey: 'primary' },
      },
      {
        id: compiledId('char_perf', 'motion'),
        time: 3,
        action: 'playMotion',
        params: {
          id: 'tomori',
          motion: { kind: 'resource', key: 'nod' },
        },
        source: { statementId: 'char_perf', outputKey: 'motion' },
      },
      {
        id: compiledId('char_perf', 'expression'),
        time: 3,
        action: 'setExpression',
        params: {
          id: 'tomori',
          expression: 'smile',
        },
        source: { statementId: 'char_perf', outputKey: 'expression' },
      },
      {
        id: compiledId('char_perf', 'lookAt'),
        time: 3,
        action: 'characterLookAt',
        params: {
          id: 'tomori',
          target: 'camera',
          point: [0.5, 0.3],
          enabled: true,
          intensity: 0.7,
        },
        source: { statementId: 'char_perf', outputKey: 'lookAt' },
      },
      {
        id: compiledId('char_perf', 'blink'),
        time: 3,
        action: 'characterBlink',
        params: {
          id: 'tomori',
          enabled: true,
          interval: 2,
        },
        source: { statementId: 'char_perf', outputKey: 'blink' },
      },
      {
        id: compiledId('char_exit', 'primary'),
        time: 4.5,
        action: 'removeCharacter',
        params: {
          id: 'tomori',
          exit: 'fade',
          duration: 0.6,
          exitDuration: 0.6,
          exitEase: 'easeIn',
        },
        source: { statementId: 'char_exit', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_focus', 'primary'),
        time: 5,
        action: 'cameraMotion',
        params: {
          move: 'push',
          easing: 'decelerate',
          duration: 0.7,
          focus: { character: 'tomori', part: 'head' },
          zoom: '+=0.25',
          angle: 3,
        },
        source: { statementId: 'camera_focus', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_move', 'primary'),
        time: 6,
        action: 'cameraMotion',
        params: {
          move: 'zoom',
          easing: 'linear',
          duration: 0.9,
          target: [0.5, 0.6],
          zoom: 1.4,
          angle: 1,
        },
        source: { statementId: 'camera_move', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_follow_start', 'start'),
        time: 7,
        action: 'cameraFollow',
        params: {
          characterId: 'tomori',
          offset: [0, -0.1],
          smoothing: 0.6,
        },
        source: { statementId: 'camera_follow_start', outputKey: 'start' },
      },
      {
        id: compiledId('camera_follow_stop', 'stop'),
        time: 8,
        action: 'cameraUnfollow',
        params: {},
        source: { statementId: 'camera_follow_stop', outputKey: 'stop' },
      },
      {
        id: compiledId('camera_path', 'primary'),
        time: 9,
        action: 'cameraPath',
        params: {
          keyframes: [
            { time: 0, position: [0, 0], zoom: 1 },
            { time: 1, position: [0.5, 0.5], zoom: 1.2, label: 'mid' },
          ],
          duration: 1.5,
          ease: 'smooth',
          loop: true,
          repeat: 2,
          yoyo: true,
        },
        source: { statementId: 'camera_path', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_shake', 'primary'),
        time: 11,
        action: 'cameraShake',
        params: {
          intensity: 0.4,
          frequency: 8,
          duration: 0.5,
          decay: true,
          direction: 'horizontal',
        },
        source: { statementId: 'camera_shake', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_hitchcock', 'primary'),
        time: 12,
        action: 'cameraHitchcock',
        params: {
          characterId: 'tomori',
          targetPart: 'chest',
          screenTarget: [0.45, 0.5],
          zoomStart: 1,
          zoomEnd: 1.3,
          scaleStart: 1,
          scaleEnd: 0.85,
          duration: 1.1,
          ease: 'easeInOut',
        },
        source: { statementId: 'camera_hitchcock', outputKey: 'primary' },
      },
      {
        id: compiledId('camera_reset', 'primary'),
        time: 13.5,
        action: 'cameraReset',
        params: {
          duration: 0.4,
          ease: 'smooth',
        },
        source: { statementId: 'camera_reset', outputKey: 'primary' },
      },
      {
        id: compiledId('env_set', 'primary'),
        time: 14,
        action: 'setEnvironmentLayer',
        params: {
          layerId: 'background',
          image: 'background/classroom.png',
          x: 0.5,
          y: 0.5,
          scale: 1,
          duration: 0.5,
          transition: 'crossFade',
        },
        source: { statementId: 'env_set', outputKey: 'primary' },
      },
      {
        id: compiledId('env_transform', 'primary'),
        time: 15,
        action: 'transformEnvironmentLayer',
        params: {
          layerId: 'background',
          x: 0.55,
          y: 0.5,
          scale: 1.05,
          duration: 0.4,
          ease: 'linear',
        },
        source: { statementId: 'env_transform', outputKey: 'primary' },
      },
      {
        id: compiledId('env_remove', 'primary'),
        time: 16,
        action: 'removeEnvironmentLayer',
        params: {
          layerId: 'background',
          duration: 0.3,
          transition: 'fadeOut',
        },
        source: { statementId: 'env_remove', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_filter_add', 'primary'),
        time: 17,
        action: 'addLensFilter',
        params: {
          category: 'grade',
          recipeId: 'builtin:cinematic-cold',
          intensity: 0.8,
          duration: 0.6,
        },
        source: { statementId: 'visual_filter_add', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_filter_change', 'primary'),
        time: 17.5,
        action: 'changeLensFilter',
        params: {
          category: 'atmosphere',
          fromCategory: 'grade',
          fromRecipeId: 'builtin:cinematic-cold',
          recipeId: 'builtin:haze-godray',
          warmth: -0.2,
          duration: 0.5,
        },
        source: { statementId: 'visual_filter_change', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_filter_reset', 'primary'),
        time: 17.75,
        action: 'resetLensFilters',
        params: { duration: 0.4 },
        source: { statementId: 'visual_filter_reset', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_object_set', 'primary'),
        time: 18,
        action: 'setCompositeRecipe',
        params: {
          targetId: 'tomori',
          slot: 'integration',
          recipeId: 'stage-match',
          mode: 'latching',
          blend: 0.7,
        },
        source: { statementId: 'visual_object_set', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_object_mod', 'primary'),
        time: 18.5,
        action: 'modulateComposite',
        params: {
          targetId: 'tomori',
          slot: 'integration',
          mode: 'envelope',
          contamination: 0.3,
          duration: 0.4,
        },
        source: { statementId: 'visual_object_mod', outputKey: 'primary' },
      },
      {
        id: compiledId('visual_object_reset', 'primary'),
        time: 19,
        action: 'resetCompositeRecipe',
        params: {
          targetId: 'tomori',
          slot: 'integration',
        },
        source: { statementId: 'visual_object_reset', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_preset', 'primary'),
        time: 19.5,
        action: 'setLighting',
        params: {
          preset: 'dramatic',
          intensity: 0.9,
        },
        source: { statementId: 'lighting_preset', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_preset_reset', 'primary'),
        time: 20,
        action: 'resetLighting',
        params: {},
        source: { statementId: 'lighting_preset_reset', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_blur', 'primary'),
        time: 20.5,
        action: 'setBlur',
        params: {
          target: 'background',
          intensity: 0.2,
        },
        source: { statementId: 'lighting_blur', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_godrays', 'primary'),
        time: 21,
        action: 'setGodrays',
        params: {
          duration: 0.5,
          angle: 45,
          lacunarity: 2.5,
        },
        source: { statementId: 'lighting_godrays', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_post_reset', 'primary'),
        time: 22,
        action: 'resetPostProcessing',
        params: { target: 'panorama' },
        source: { statementId: 'lighting_post_reset', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_overlay', 'primary'),
        time: 22.5,
        action: 'addColorOverlay',
        params: {
          id: 'overlay_1',
          color: '#fff',
          intensity: 0.3,
        },
        source: { statementId: 'lighting_overlay', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_overlay_remove', 'primary'),
        time: 23,
        action: 'removeColorOverlay',
        params: {
          id: 'overlay_1',
        },
        source: { statementId: 'lighting_overlay_remove', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_overlay_clear', 'clear'),
        time: 23.5,
        action: 'clearColorOverlays',
        params: {},
        source: { statementId: 'lighting_overlay_clear', outputKey: 'clear' },
      },
      {
        id: compiledId('lighting_point', 'primary'),
        time: 24,
        action: 'addPointLight',
        params: {
          id: 'point_1',
          color: '#ffe',
          radius: 120,
          x: 768,
          y: 324,
        },
        source: { statementId: 'lighting_point', outputKey: 'primary' },
      },
      {
        id: compiledId('lighting_point_clear', 'clear'),
        time: 24.5,
        action: 'clearPointLights',
        params: {},
        source: { statementId: 'lighting_point_clear', outputKey: 'clear' },
      },
      {
        id: compiledId('audio_bgm_play', 'primary'),
        time: 25,
        action: 'setBGM',
        params: {
          file: 'bgm/opening.ogg',
          volume: 0.4,
          loop: true,
          fadeIn: 1,
        },
        source: { statementId: 'audio_bgm_play', outputKey: 'primary' },
      },
      {
        id: compiledId('audio_bgm_stop', 'stop'),
        time: 26,
        action: 'stopAudio',
        params: {
          id: 'bgm',
          fadeOut: 0.8,
        },
        source: { statementId: 'audio_bgm_stop', outputKey: 'stop' },
      },
      {
        id: compiledId('audio_sfx_play', 'primary'),
        time: 27,
        action: 'playAudio',
        params: {
          id: 'door',
          file: 'sfx/door.ogg',
          volume: 0.7,
          duration: 1.2,
        },
        source: { statementId: 'audio_sfx_play', outputKey: 'primary' },
      },
      {
        id: compiledId('audio_sfx_stop', 'stop'),
        time: 28,
        action: 'stopAudio',
        params: {
          id: 'door',
          fadeOut: 0.2,
        },
        source: { statementId: 'audio_sfx_stop', outputKey: 'stop' },
      },
      {
        id: compiledId('graphic_image_set', 'primary'),
        time: 29,
        action: 'addImage',
        params: {
          id: 'poster',
          file: 'images/poster.png',
          position: [0.5, 0.5],
        },
        source: { statementId: 'graphic_image_set', outputKey: 'primary' },
      },
      {
        id: compiledId('graphic_image_transform', 'primary'),
        time: 30,
        action: 'transformImage',
        params: {
          id: 'poster',
          scale: 1.2,
          duration: 0.5,
        },
        source: { statementId: 'graphic_image_transform', outputKey: 'primary' },
      },
      {
        id: compiledId('graphic_image_remove', 'primary'),
        time: 31,
        action: 'removeImage',
        params: {
          id: 'poster',
        },
        source: { statementId: 'graphic_image_remove', outputKey: 'primary' },
      },
      {
        id: compiledId('graphic_text_set', 'primary'),
        time: 32,
        action: 'addTextLayer',
        params: {
          id: 'caption',
          text: 'Title',
          fontFamily: 'Inter',
          fontSize: 32,
          color: '#fff',
        },
        source: { statementId: 'graphic_text_set', outputKey: 'primary' },
      },
      {
        id: compiledId('graphic_text_transform', 'primary'),
        time: 33,
        action: 'transformTextLayer',
        params: {
          id: 'caption',
          opacity: 0.5,
          duration: 0.4,
        },
        source: { statementId: 'graphic_text_transform', outputKey: 'primary' },
      },
      {
        id: compiledId('graphic_text_remove', 'primary'),
        time: 34,
        action: 'removeTextLayer',
        params: {
          id: 'caption',
        },
        source: { statementId: 'graphic_text_remove', outputKey: 'primary' },
      },
      {
        id: compiledId('custom_anim', 'primary'),
        time: 35,
        action: 'playCustomAnimation',
        params: {
          target: 'poster',
          file: 'effects/sparkle.json',
          duration: 1,
          loop: false,
        },
        source: { statementId: 'custom_anim', outputKey: 'primary' },
      },
    ]);
  });
});
